version: "2"

run:
  timeout: 5m

linters:
  default: all
  disable:
    - exhaustruct
    - depguard
    - wsl
  settings:
    lll:
      line-length: 120
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
          - funlen
          - gocognit
          - cyclop
          - maintidx
          - mnd
          - goconst
          - forcetypeassert
          - err113
          - paralleltest
          - prealloc
          - testpackage
          - varnamelen

formatters:
  enable:
    - gofumpt
    - gci
  settings:
    gofumpt:
      extra-rules: true
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/brunorene/go-plumber)
      custom-order: true
